### ISSUE TITLE
Change navbar background color to #FFFFFF

### ISSUE THREAD

**Issue by luizabrito-pm** [RibonDAO/interface#249]
## Details
Currently is: #FBFBFD 
Change it for: #FFFFFF

![image](https://user-images.githubusercontent.com/107929760/175023197-84c19796-06a8-4e9d-82cc-06858e63bddb.png)

## Standard Definition of Done
* Features and screens must have been tested on mobile and desktop - ensuring responsiveness;
* Unit tests must have been created;
* Features must have met all acceptance criteria;
* Translation documents must have been updated (for features and changes involving the interface and copywriting).

## Are you getting started?
Check [Ribon Docs](https://ribondao.github.io/docs/) to learn what is Ribon, how to contribute and get a Smart contract overview.

## Questions? Join Discord!
We highly recommend that you join us in [Discord #development channel](https://discord.gg/APAKvaSuMN) to ask questions quickly and hear about upcoming new issues.

**Comment by bilalscripts** [comment]
hey assign it to me, I want to do it.
