### ISSUE TITLE
Align text of cause cards to the left

### ISSUE THREAD

**Issue by luizabrito-pm** [RibonDAO/interface#253]
## Details
Screen: https://dapp.ribon.io/

Text in question highlighted by red frame:
![image](https://user-images.githubusercontent.com/107929760/175104860-3de6e50c-a2e6-4522-8ea4-484cc01181cf.png)

## Standard Definition of Done
* Features and screens must have been tested on mobile and desktop - ensuring responsiveness;
* Unit tests must have been created;
* Features must have met all acceptance criteria;
* Translation documents must have been updated (for features and changes involving the interface and copywriting).

## Are you getting started?
Check [Ribon Docs](https://ribondao.github.io/docs/) to learn what is Ribon, how to contribute and get a Smart contract overview.

## Questions? Join Discord!
We highly recommend that you join us in [Discord #development channel](https://discord.gg/APAKvaSuMN) to ask questions quickly and hear about upcoming new issues.

**Comment by Isaac-alencar** [comment]
@luizabrito-pm Hi, I would like to work on that, can you assign it to me?
