### ISSUE TITLE
Wallet connection loading

### ISSUE THREAD

**Issue by luizabrito-pm** [RibonDAO/interface#512]
## Details
**Is your feature request related to a problem? Please describe.**
Contribution flow transparency (USDC deposit in the treasury) in the protocol

**Describe the solution you'd like**
Given that the user clicked to connect to the wallet then the loader will appear until it returns success or failure.

**Additional context**
[Figma design handoff file](https://www.figma.com/file/doJ8RzbLicyI1pPub6FDo8/RibonDAO-GitHub?node-id=9%3A786)

In Figma design handoff file you will find:
* Components to be implemented
* Visual reference for page implementation
* Color scheme and fonts following Ribon's visual identity
* Events that must be implemented to be logged during user interaction with the dApp (they detailed in the handoff comments)

## Standard Definition of Done
* Features and screens must have been tested on mobile and desktop - ensuring responsiveness;
* Unit tests must have been created;
* Features must have met all acceptance criteria;
* Translation documents must have been updated (for features and changes involving the interface and copywriting).

## Are you getting started?
Check [Ribon Docs](https://ribondao.github.io/docs/) to learn what is Ribon, how to contribute and get a Smart contract overview.

## Get rewarded in USDC
We have USDC bountys for all our issues on Github. If you want to get rewarded for solving this issue just follow these steps:
- Click on [this link](https://app.dework.xyz/ribon/tech-93605?taskId=a0433390-fd1c-4b55-b7c5-ac26d9305d1b) to access this issue on Ribons Dework.
- Log in using your Github account, and add your metamask wallet.
- Make sure you're in the right issue, then click on "submit work" to apply.
- You'll be added to our discord and a thread will be automaticaly created so you can talk with the reviewer. You can ask questions or simply ask to work on the issue and we will assign it to you.
- When you're done, link your pool request. We will review your work and send the USDC to the wallet you added on dework. 

## Questions? Join Discord!
We highly recommend that you join us in [Discord #development channel](https://discord.gg/APAKvaSuMN) to ask questions quickly and hear about upcoming new issues.

**Comment by mspilimbergo** [comment]
The Figma handoff doc is not public - I was not able to access it.

**Comment by luizabrito-pm** [comment]
Hey @mspilimbergo , can you try again? https://www.figma.com/file/doJ8RzbLicyI1pPub6FDo8/RibonDAO-GitHub?node-id=0%3A1 I adjusted the sharing settings.

**Comment by mspilimbergo** [comment]
Yes, I can access it now. Thanks!
